#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the navbar)
name: Jacob Finton

# Your site's title 
title: Jacobs-Website

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: My website

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: My website

# The full URL to your site. Note: site.github.url will be used by default.
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# URL to a site-wide logo (e.g., /assets/your-company-logo.png)
logo: /assets/images/Rocco.jpg

permalink: /:year/:month/:day/:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: 
  twitter: 
  github: jacobfinton
  gitlab: jacobfinton
  linkedin: 

plugins:
  - jekyll-feed
  - jekyll-sitemap

